# Generated by Django 5.2 on 2025-05-16 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsuarios',
            fields=[
                ('cod_tab', models.AutoField(primary_key=True, serialize=False)),
                ('des_nome', models.CharField(blank=True, max_length=200)),
                ('des_login', models.EmailField(max_length=200, unique=True)),
                ('des_senha', models.CharField(max_length=500)),
                ('dta_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_usuarios',
            },
        ),
    ]
