# Generated by Django 5.2 on 2025-06-22 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_posts',
            fields=[
                ('cod_tab', models.AutoField(primary_key=True, serialize=False)),
                ('dta_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('des_mensagem', models.CharField(blank=True, max_length=1000)),
                ('flg_comentario', models.EmailField(blank=True, max_length=1)),
                ('dta_atualizacao', models.DateTimeField(auto_now=True)),
                ('cod_post', models.ForeignKey(db_column='cod_post', on_delete=django.db.models.deletion.RESTRICT, to='appposts.tbl_posts')),
                ('cod_usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_posts',
            },
        ),
    ]
